// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1OzK3wuRbD42U5FdCBUizGMy38lciDo',
    appId: '1:290936825862:web:2e68b7b7a035f8a76dfb87',
    messagingSenderId: '290936825862',
    projectId: 'cmsc23-todo-app-komercado',
    authDomain: 'cmsc23-todo-app-komercado.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-komercado.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0etzRd5r56rE1y8FApHHvMFVznLWLp2Y',
    appId: '1:290936825862:android:d38c9fd1f5862dab6dfb87',
    messagingSenderId: '290936825862',
    projectId: 'cmsc23-todo-app-komercado',
    storageBucket: 'cmsc23-todo-app-komercado.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE2hQlYIlOZ50YmVNE8xg8LXz1-l6C7ig',
    appId: '1:290936825862:ios:aff7e51eac7c97546dfb87',
    messagingSenderId: '290936825862',
    projectId: 'cmsc23-todo-app-komercado',
    storageBucket: 'cmsc23-todo-app-komercado.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE2hQlYIlOZ50YmVNE8xg8LXz1-l6C7ig',
    appId: '1:290936825862:ios:aff7e51eac7c97546dfb87',
    messagingSenderId: '290936825862',
    projectId: 'cmsc23-todo-app-komercado',
    storageBucket: 'cmsc23-todo-app-komercado.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi1OzK3wuRbD42U5FdCBUizGMy38lciDo',
    appId: '1:290936825862:web:47dd86472f7f01706dfb87',
    messagingSenderId: '290936825862',
    projectId: 'cmsc23-todo-app-komercado',
    authDomain: 'cmsc23-todo-app-komercado.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-komercado.appspot.com',
  );
}
